### PR TITLE
#1066 Capitalization across Community Platform

### LINKED ISSUE #1066: Capitalization across Community Platform
**Describe the bug**
Humans are forgetful beings :) I could win a Guinness for that.
People uploading how-tos and content on the Community Platform could (and will) forget to capitalize their text. Which in turn looks amateur/less professional. Would be really good to run a script to capitalize the first letter of the following:

1. How-to 
1.1 How-to cover title and description
1.2 How-to steps title and description

2. Profiles
2.1 Name and description

3. Events? (can't see as there are no events :( )

**To Reproduce**
[Here](https://community.preciousplastic.com/how-to/bending-with-the-sheetpress) you can reproduce the error (all lowercase)

Capitalize

Big up you devs out there!

### LINKED ISSUE #1166: Capitalize titles
Would be great to have all titles capitalized (first letter) so we can rule out user mistakes

image

### PR DESCRIPTION
**Pull request by prolland006**
PR Type

- [x] New feature (non-breaking change which adds functionality)

PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)
- [x] - Passes Tests

## Description

_What this PR does_

## Git Issues

Closes #1066
Closes #1166

## Screenshots/Videos

image

### CODE REVIEW

File: src/components/Form/Fields.tsx [hunk 1]
```diff
@@ -25,6 +26,9 @@ interface IDatePickerFieldProps extends IFieldProps {
   customChange?: (location) => void
 }
 
+const toCapitalizedFirstletterInput = e => {
+  e.target.value = capitalizeFirstLetter(e.target.value)
```
Comment (catx23) [inline src/components/Form/Fields.tsx:30]: Hey, lot's of great work doing !

1. I am not quite sure it's a good idea to modify the event.value
2. Since anything under /components/form could be understood as generic widget library, I'd make the capitalization explicit via property. There might be quite a number of cases where you don't want it; saying this with a long experience developing widget libraries :-)

**Comment by chrismclarke** [comment]
Thanks for looking into this, I like the idea to force the capitalization in the input fields themselves. 

As this has been outstanding for quite a while (sorry about that again!) I've just merged the latest master and resolved conflicts. I also refactored the field modifiers so that they could be used with existing fields (adding `modifiers:{capitalization:true}` to existing `InputField` and textfield elements instead of relying on a `FormattedInputField` element) - in case we want to add more of these modifiers in the future.

Also, as we have quite a lot of outstanding howtos etc. that aren't currently capitalised I've added a temporary method to capitalize existing howto titles and descriptions on render (easier than migrating the existing db at this stage)

So as it stands the following should now be capitalized for new forms:
- howto title, description, step-title, step description
- event title

@davehakkens - is this enough for now to merge or do you also want to include anything else to be capitalized?

**Review by chrismclarke — APPROVED** [review]

**Comment by davehakkens** [comment]
perfect! looks really nice :)
