### PR TITLE
#676 Received a broken How-to page #651 sign-in page accessible to logged-in users

### LINKED ISSUE #651: The sign-in page is accessible to logged-in users
**Describe the bug**
Currently logged-in users were able to open the log-in page with its url, /sign-in

**To Reproduce**
23ab619c445e4e1f244a3fd8cbe193754036b1c6

**Expected behavior**
Users should be redirected to the home page instead

### LINKED ISSUE #676: Received a broken How-to page when opening a unknown how-to
**Describe the bug**
When visiting /how-to/unknown-anything, the page was as below
image

**To Reproduce**
5a266775073243f6fa702a9e94351a6f727d7c12

**Expected behavior**
Just show the 404 page for any nonexistent resource

image

### PR DESCRIPTION
**Pull request by prolland006**
PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)
- [ ] - Passes Tests

## Description

_What this PR does_

## Git Issues

Closes #676
Closes #651

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

### CODE REVIEW

File: src/pages/SignIn/SignIn.tsx [hunk 1]
```diff
@@ -117,6 +118,10 @@ class SignInPage extends React.Component<IProps, IState> {
 
   public render() {
     const { authProvider, notificationProps } = this.state
+    if (this.props.userStore!.user) {
+      // User logged in
+      return <Redirect to={'/'} />
```
Comment (chrismclarke) [inline src/pages/SignIn/SignIn.tsx:123]: Thanks for adding this!

File: src/pages/Howto/Content/Howto/Howto.tsx [hunk 2]
```diff
@@ -149,13 +150,7 @@ export class Howto extends React.Component<
...
       )
     } else {
-      return isLoading ? (
-        <Loader />
-      ) : (
-        <Text txtcenter mt="50px" width={1}>
-          How-to not found
-        </Text>
-      )
+      return isLoading ? <Loader /> : <Route component={NotFoundPage} />
```
Comment (chrismclarke) [inline src/pages/Howto/Content/Howto/Howto.tsx:153]: Looks good

File: debug.log [hunk 3]
```diff
@@ -0,0 +1 @@
+[1027/094351.774:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
```
Comment (chrismclarke) [inline debug.log:1]: I'll add to gitignore for all `.log` files so fine to leave this

**Review by chrismclarke — APPROVED** [review]
Thanks for adding these! Merging
