### PR TITLE
Fix #762: profile links

### LINKED ISSUE #762: Incorrect contacts/links in Profile
**Describe the bug**
All links/contacts were prefixed with http://localhost:3456/u/<link>
image

**To Reproduce**
Open a profile that has contacts & links. Click on any of them and users are taken

**Expected behavior**
- Users should open contacts/links correctly

### PR DESCRIPTION
**Pull request by lauvrenn**
closes #762

### CODE REVIEW

File: src/utils/validators.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import isUrl from 'is-url'
+
+/****************************************************************************
+ *            General Validation Methods
+ * **************************************************************************/
+
+const validateUrl = async (value: any) => {
+  console.log('val here')
+  console.log('val ', value)
+  return value ? (isUrl(value) ? undefined : 'Invalid url') : 'Required'
```
Comment (drydenwilliams) [inline src/utils/validators.ts]: Please could we not use nested ternaries. Would prefer something more readable.

File: src/utils/validators.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+}
+
+const addProtocol = (ev: any) => {
+  const val = ev.target.value
+  console.log('addprot ', val, ' ', ev.target.initialValue)
+  ev.target.initialValue = val.indexOf('://') === -1 ? 'http://' + val : val
```
Comment (drydenwilliams) [inline src/utils/validators.ts]: should it be a template literal `http://${val}` also maybe: `://${val}` as it should be on `https://`?

Comment (lauvrenn) [reply src/utils/validators.ts]: yep, it was in progress so I hadn't changed it yet then

File: src/utils/validators.ts (hunk 1 above)
Comment (lauvrenn) [reply src/utils/validators.ts]: I just moved this func from somewhere else and didn't mess with it, but I get you. This particular ternary is moderately readable though I think.

**Comment by lauvrenn** [comment]
thanks! Oh, I didn't realize there were other types than links there :no_mouth: thanks for fixing that! 

If I remember correctly, I think only mutators worked `onBlur`, validations showed up on form submit instead. If that's the case, email validation should work then

File: src/utils/validators.ts (hunk 1 above)
Comment (drydenwilliams) [reply src/utils/validators.ts]: Why is this an `async` function?

Comment (drydenwilliams) [reply src/utils/validators.ts]: Also I would prefer to read it rather than it be "moderately readable". Just for new starters/debugging it's just way easier if it's something like: 

```
if (isUrl(value)) {
 return 'Invalid URL';
}

return 'Required';
```

File: src/utils/validators.ts [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+const required = (value: any) => (value ? undefined : 'Required')
+
+const validateUrl = async (value: any) => {
+  return value ? (isUrl(value) ? undefined : 'Invalid url') : 'Required'
+}
+
+const validateEmail = (value: string) => {
+  console.log('isEmail', isEmail(value))
+
+  return value ? (isEmail(value) ? undefined : 'Invalid email') : 'Required'
```
Comment (drydenwilliams) [inline src/utils/validators.ts]: Same for the point above. I know it's nice to be on one line, but I still find this confusing. Takes me a while to compute it rather than something like: 

```
if (isEmail(value)) {
  return something
}

return 'Required';
```

File: src/utils/validators.ts [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+  const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
+  return re.test(String(email).toLowerCase())
+}
+
+/****************************************************************************
+ *            FORM MUTATORS
+ * **************************************************************************/
+
+const addProtocol = ([name], state, { changeValue }) => {
+  changeValue(state, name, (val: string) =>
```
Comment (drydenwilliams) [inline src/utils/validators.ts]: Could we just do `://` and then it would resolve to either `http` or `https`? @BenGamma @chrismclarke

File: src/utils/validators.ts [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+}
+
+const validateEmail = (value: string) => {
+  console.log('isEmail', isEmail(value))
+
+  return value ? (isEmail(value) ? undefined : 'Invalid email') : 'Required'
+}
+
+const isEmail = (email: string) => {
+  const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
```
Comment (drydenwilliams) [inline src/utils/validators.ts]: Please could you add the link where you got this from in a comment

Comment (lauvrenn) [reply src/utils/validators.ts]: @BenGamma

File: src/utils/validators.ts (hunk 4 above)
Comment (lauvrenn) [reply src/utils/validators.ts]: I don't know if I understand you correctly here, but `http` resolves to `https` though

**Comment by lauvrenn** [comment]
@BenGamma is this one up for merging yet?

File: src/utils/validators.ts (hunk 4 above)
Comment (BenGamma) [reply src/utils/validators.ts]: Yes an http site that allow https will redirect to it anyway, so no worries here 🤗

**Comment by BenGamma** [comment]
This one needed a little bit of extra work :
- I fixed the issue with the onBlur method. Was tricky to get it working on both validators and mutators, because they were overriding the `onBlur()` method of each others. I had to create a `customOnBlur` to trigger both of them.
- Cleared the links in the profile page with a `mailto:` prefix for emails, display the discord ID of the user instead of "Discord" and link to the precious plastic discord ([you can't create link to discord profile yet](https://support.discordapp.com/hc/en-us/community/posts/360041519131-UserProfilesLinks))
- fix some icons display for social-media links
- fix the tests
Ready to go now 🚀
