### PR TITLE
feat: migrate useful voting, add new useful aggregation & fix useful counts

### LINKED ISSUE #2231: [bug] Useful votes not working correctly
**Describe the bug**
Useful count is not working as intended, it seems like the aggregations are messing up and that clicking useful on a howto or research is affecting another unrelated item. This is most likely related to the bugs that have been reported by @thisismattia 

It seems to me like all of the research aggregations may not be actually working properly and that only the howto aggregations are working but still affecting the research articles like seen in the video below.

**To Reproduce**
Follow steps like in video:

At the start the Howto has a useful count of 1, after a research useful count is decreased it also affects the howto's count. They seem to be interlinked.

https://user-images.githubusercontent.com/652368/233655059-fe1ebcde-aa80-4100-99c7-1e624dc8040b.mov

**Expected behaviour**
Clicking useful on a Research or Howto should not affect entities that are not the specific one in question

### LINKED ISSUE #2277: [bug] Useful counter profile not accurate
**Describe the bug**
We recently introduced the useful counter on profiles here https://github.com/ONEARMY/community-platform/pull/2233  (only visable for beta-testers)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [research overview](https://community.projectkamp.com/research) to see the gathered useful
2. Compare with the[ user profile](https://community.projectkamp.com/u/projectkamp)(make sure you are a beta-tester to see total useful in profile)

**Expected behaviour**
It should show the total amount of useful in the profile

**Screenshots**
Total useful on Project Kamp Profile (4)
afbeelding

Total useful this account got (+40)
afbeelding

### PR DESCRIPTION
**Pull request by iSCJT**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

This pr introduces a number of changes related to the 'useful' functionality for research and how-to articles:

- Migrates the useful voting data from the user object to individual how to and research docs.
- Introduces a new totalUseful aggregation that calculates useful across both object types.
- Introduces an update db function that can take partial docs to be updated.
- Deprecates old useful aggregations.

## Git Issues

Closes #2277 Closes #2231 

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

File: src/pages/Howto/Content/Howto/Howto.tsx [hunk 1]
```diff
@@ -1,35 +1,35 @@
...
 import WhiteBubble0 from 'src/assets/images/white-bubble_0.svg'
 import WhiteBubble1 from 'src/assets/images/white-bubble_1.svg'
 import WhiteBubble2 from 'src/assets/images/white-bubble_2.svg'
 import WhiteBubble3 from 'src/assets/images/white-bubble_3.svg'
-import type { UserStore } from 'src/stores/User/user.store'
-import { HowToComments } from './HowToComments/HowToComments'
-import type { AggregationsStore } from 'src/stores/Aggregations/aggregations.store'
-import { seoTagsUpdate } from 'src/utils/seo'
-import { Link } from 'react-router-dom'
+import { trackEvent } from 'src/common/Analytics'
```
Comment (thisislawatts) [inline src/pages/Howto/Content/Howto/Howto.tsx:24]: **nitpick(non-blocking)**: @iSCJT there seems to be some formatter in your IDE which is performing some kind of sort on the imports. This introduces some noise to the diffs, could we either:
* Add a linting rule which formalises this convention and format the entire code base (seperate PR).
* Disable the formatting extension whilst working on the Platform codebase.

Comment (iSCJT) [reply src/pages/Howto/Content/Howto/Howto.tsx:24]: @thisislawatts I'd noticed that.  It was vs code's built in import sorter doing it but I've disabled for the project and added aslant rules to do it now.

https://github.com/ONEARMY/community-platform/pull/2345

Comment (iSCJT) [reply src/pages/Howto/Content/Howto/Howto.tsx:24]: Will look at the test fails in the morning

File: src/stores/databaseV2/DocReference.tsx
Comment (iSCJT) [inline src/stores/databaseV2/DocReference.tsx:1]: Added an update function so that we don't need to replace the full document every time.

File: src/stores/Aggregations/aggregations.store.tsx [hunk 2]
```diff
@@ -44,9 +45,13 @@ export class AggregationsStore {
     makeAutoObservable(this, { aggregations: observable })
   }
 
-  @action
-  private updateAggregationValue(aggregationId: IAggregationId, value: any) {
-    this.aggregations[aggregationId] = value
+  /**
+   * fetch specific value for aggregation given id and aggregationid
+   */
+  public getAggregationValue(aggregationId: IAggregationId, id: string) {
```
Comment (iSCJT) [inline src/stores/Aggregations/aggregations.store.tsx:51]: added function to retrieve aggregation value for specific user / id

File: src/modules/admin/pages/adminDatabase.tsx
Comment (iSCJT) [inline src/modules/admin/pages/adminDatabase.tsx:1]: Added a simple page within the admin section to initiate the migration.  If there's a better or preferred way to initiate then please let me know.

File: src/common/hooks/userStats.ts
Comment (iSCJT) [inline src/common/hooks/userStats.ts:1]: Added a user stats hook, intention is to also add in other stats required for profile page or elsewhere as part of another pr.

File: functions/src/aggregations/migrations.ts
Comment (iSCJT) [inline functions/src/aggregations/migrations.ts:1]: Script that migrates existing user object voted useful array data to the how to and research docs.

File: src/stores/Aggregations/aggregations.store.tsx [hunk 3]
```diff
@@ -87,6 +92,11 @@ export class AggregationsStore {
     this.setSubscriptionTimeout(aggregationId, 0)
   }
 
+  @action
```
Comment (iSCJT) [inline src/stores/Aggregations/aggregations.store.tsx:95]: Change not made to functionality, just moved private function after public ones.

**Comment by davehakkens** [comment]
Some feedback from looking at the preview link.
When something is **marked** as `useful` it has a different state, but this "marked as useful" one seems to be removed 
Should be this: 
afbeelding

File: src/pages/Howto/Content/Howto/Howto.tsx [hunk 4]
```diff
@@ -1,36 +1,37 @@
...
+import { isUserVerifiedWithStore } from 'src/common/isUserVerified'
```
Comment (thisislawatts) [inline src/pages/Howto/Content/Howto/Howto.tsx:30]: **issue:** There seems to be a duplicate import here, this causes failing builds locally.

File: src/models/common.models.tsx [hunk 5]
```diff
@@ -47,3 +47,16 @@ interface ILatLng {
   lat: number
   lng: number
 }
+
+export interface IVotedUseful {
+  votedUsefulBy?: string[]
+  votedUsefulCount?: number
```
Comment (thisislawatts) [inline src/models/common.models.tsx:53]: **question:** Why are we storing this property on the model? It seems like a useful computed property on the store for use within our application but it doesn't seem worth persisting to the DB. Is there some context I am missing about this change?

File: src/modules/admin/pages/adminDatabase.tsx
Comment (thisislawatts) [reply src/modules/admin/pages/adminDatabase.tsx:1]: This is very useful but I don't think we would expect an admin user to make this change, the migration is something that needs to be co-ordinated with the release to minimise the time where Useful counts will be shown as 0.

File: src/models/common.models.tsx (hunk 5 above)
Comment (iSCJT) [reply src/models/common.models.tsx:53]: @thisislawatts I've remembered why I changed it...  I wanted to limit the records that were being queried by the aggregation and firebase doesn't support using array length in a where clause.  Example:

image

Comment (thisislawatts) [reply src/models/common.models.tsx:53]: @iSCJT did you experiment with the following? I found some mixed messaging online but it seems like the following for check for any documents where the list is not empty. 

```ts
const howtos = await db
  .collection(DB['howtos'])
  .where('_createdBy', '==', id)
  .where('votedUseful', '!=', [])
  .get()
```

Comment (iSCJT) [reply src/models/common.models.tsx]: @thisislawatts thanks, I've done some testing and that seems to work 👍

File: packages/components/src/UsefulStatsButton/UsefulStatsButton.tsx [hunk 6]
```diff
@@ -26,14 +28,19 @@ export const UsefulStatsButton = (props: IProps) => {
     () => setVotedUsefulCount(props.votedUsefulCount),
```
Comment (thisislawatts) [inline packages/components/src/UsefulStatsButton/UsefulStatsButton.tsx:28]: **Suggestion:** Lift the `{votedUsefulCount ?? 0}` out of the JSX and into the `setVotedUsefulCount`

```suggestion
    () => setVotedUsefulCount(props.votedUsefulCount || 0),
```

Maybe also worth adding a default value when invoking `useState`.  

_Note:_ I switched to using the logical OR operator `||` this is because the nullish coalescing operator is specifically designed to handle null or undefined values. It treats other falsy values (such as empty strings, 0, and false) as truthy values whereas in those scenarios we would prefer to show `0`.

```ts
false ?? 0 // false
'' ?? 0 // ''
```

File: src/stores/Aggregations/aggregations.store.tsx (hunk 2 above)
Comment (thisislawatts) [reply src/stores/Aggregations/aggregations.store.tsx:51]: **question:** Is the `id` parameter here always a user id or could it be anything?

**Comment by thisislawatts** [comment]
Pulling the branch down locally, I see the same as @davehakkens which seems to be from the boolean value not being updated:

https://github.com/ONEARMY/community-platform/assets/472589/49ade2dc-0a69-4a02-8a17-2c3c22f9dfa3

File: src/models/research.models.tsx [hunk 7]
```diff
@@ -1,30 +1,31 @@
...
   /** The main research item, as created by a user */
   export type Item = {
     updates: Update[]
     mentions?: UserMention[]
     _createdBy: string
-    total_views?: number
     collaborators: string[]
-    subscribers?: UserIdList
-  } & Omit<FormInput, 'collaborators'>
+    subscribers?: string[]
```
Comment (thisislawatts) [inline src/models/research.models.tsx:26]: **question:** Any reason to remove the `UserIdList`  type here?

Comment (iSCJT) [reply src/models/research.models.tsx:26]: Will have been because it was a locally defined (row 15) simple type that wasn't used elsewhere.

File: src/stores/Aggregations/aggregations.store.tsx (hunk 2 above)
Comment (iSCJT) [reply src/stores/Aggregations/aggregations.store.tsx:51]: At the moment it would only be a user id but I've left it generic as in future I could see us having aggregations where the subject was a howto or research id for instance.  Number of views or downloads or something along those lines.

File: src/modules/admin/pages/adminDatabase.tsx
Comment (iSCJT) [reply src/modules/admin/pages/adminDatabase.tsx:1]: yea I was expecting it to be something ran by me or another maintainer on upgrade rather than an admin, wasn't sure how you usually triggered upgrade scripts?  Happy to drop the page and have some other mechanism.

File: packages/components/src/UsefulStatsButton/UsefulStatsButton.tsx (hunk 6 above)
Comment (iSCJT) [reply packages/components/src/UsefulStatsButton/UsefulStatsButton.tsx:28]: Makes sense, I'll fix in the morning.

File: src/models/user.models.tsx [hunk 8]
```diff
@@ -43,8 +43,10 @@ export interface IUser {
   year?: ISODateString
   stats?: IUserStats
   /** keep a map of all howto ids that a user has voted as useful */
+  /** 25/05/2023 this will be deprecated but required during migration of useful to how-to object */
   votedUsefulHowtos?: { [howtoId: string]: boolean }
   /** keep a map of all Research ids that a user has voted as useful */
+  /** 25/05/2023 this will be deprecated but required during migration of useful to how-to object */
```
Comment (thisislawatts) [inline src/models/user.models.tsx:49]: **suggestion:** Rather than a comment that can be easily lost can we please create an Issue related to this for better visibility and include a link to it here.

**Review by thisislawatts — APPROVED** [review]
