### PR TITLE
fix: map page missing flags

### LINKED ISSUE #2171: bug: map pins rendering with unknown country
**Describe the bug**

All map pins are showing the `unknown-flag`

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [Map](https://community.preciousplastic.com/map)
2. Click on any map Pin
3. See error

**Expected behaviour**

Well this is a little unclear, it could show the flag for the current map pin location **OR** the flag associated with the user profile. User profile seems reasonable. 

**Screenshots**
Screenshot 2023-03-25 at 23 46 07

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Include user country so that the Username component renders a flag. 

- chore: refactor to simplify typing
- chore: remove mock pin generation code
- chore: remove unused code
- fix: pass flag through from User object
- chore: refactor to common method

Closes #2171

### CODE REVIEW

File: src/pages/Maps/Content/View/index.tsx [hunk 1]
```diff
@@ -38,27 +31,15 @@ interface IInjectedProps extends IProps {
...
   // on move end want to calculate current bounding box and notify parent
   static defaultProps: Partial<IProps> = {
-    onBoundingBoxChange: () => null,
     onPinClicked: () => null,
     pins: [],
     filters: [],
     center: { lat: 51.0, lng: 19.0 },
     zoom: 3,
   }
   // so that pins can be displayed as required
```
Comment (AlfonsoGhislieri) [inline src/pages/Maps/Content/View/index.tsx:40]: **Nitpick** this comment is a bit confusing now that the `handleMove` function has been removed

**Review by AlfonsoGhislieri — CHANGES_REQUESTED** [review]
Looks good @thisislawatts really nice to see a lot of refactoring here! Just a left over rogue comment to remove 🎉

**Review by AlfonsoGhislieri — DISMISSED** [review]

**Comment by thisislawatts** [comment]
@AlfonsoGhislieri all the tests are passing now, guessing it could have been a flake?

**Review by davehakkens — APPROVED** [review]
