### PR TITLE
fix: add countryflag to research collaborators

### LINKED ISSUE #2278: [bug] Userflags of contributors are not shown in Research
**Describe the bug** 
The country flags of the contributors are not shown in the research module

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [a research topic](https://community.projectkamp.com/research/make-a-basekamp-extension-in-a-container)
2. Scroll down the page
3. Flags are grey
4. Click the username to see the profile with original flag

**Screenshots**
afbeelding
afbeelding
afbeelding

### PR DESCRIPTION
**Pull request by AlfonsoGhislieri**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Adds contributors flags to bottom of reseach article and to updates

## Git Issues

Closes #2278

## Screenshots/Videos

image

image---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

File: src/pages/Research/Content/ResearchArticle.tsx [hunk 1]
```diff
@@ -198,10 +227,14 @@ const ResearchArticle = observer((props: IProps) => {
...
-            contributors={collaborators.map((c) => ({
-              userName: c,
-              isVerified: false,
-            }))}
+            contributors={
+              contributors.length > 0
+                ? contributors
+                : collaborators.map((c) => ({
+                    userName: c,
+                    isVerified: false,
```
Comment (AlfonsoGhislieri) [inline src/pages/Research/Content/ResearchArticle.tsx:235]: This feels very hacky to me, but the issue is that the unit tests fail because useEffect is not run when the components are rendered in jest. This causes the state to be empty and them to fail. This was the easy solution I could think of, but results in dulication of this block:

```
    const collaborators = Array.isArray(item.collaborators)
      ? item.collaborators
      : ((item.collaborators as string) || '').split(',').filter(Boolean)
```

And in general doesn't feel very clean

File: src/common/contributorData.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+          }),
+        )
+        setContributors(contributorsData)
+      }
+    }
+    fetchContributorsData()
+  }, [collaborators])
+
+  return contributors
+}
```
Comment (thisislawatts) [inline src/common/contributorData.ts:30]: **question:** Given this fn has been mocked out in each component that uses it, what do we have in place to verify that this logic is correct?

Comment (AlfonsoGhislieri) [reply src/common/contributorData.ts:30]: Currently nothing besides some eye tests and my word ;)

Jokes aside you're right this is definitely a section of code that needs coverage, will add it!

File: src/pages/Research/Content/ResearchUpdate.test.tsx [hunk 3]
```diff
@@ -9,8 +9,13 @@ import { FactoryResearchItemUpdate } from 'src/test/factories/ResearchItem'
 
 jest.mock('src/index', () => {
   return {
-    useCommonStores: jest.fn().mockReturnValue({
-      stores: { userStore: { fetchAllVerifiedUsers: jest.fn() } },
+    useCommonStores: () => ({
+      stores: {
+        userStore: {
+          fetchAllVerifiedUsers: jest.fn(),
+          getUserByUsername: jest.fn().mockResolvedValue({ country: '' }),
```
Comment (thisislawatts) [inline src/pages/Research/Content/ResearchUpdate.test.tsx:16]: **nitpick (non-blocking):** Maybe we could use the FactoryUser() here so its a full User Object and not a partial.

File: src/common/contributorData.ts [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+  useEffect(() => {
+    const fetchContributorsData = async () => {
+      if (collaborators?.length > 0) {
+        const contributorsData = await Promise.all(
+          collaborators.map(async (c) => {
+            const user = await userStore.getUserByUsername(c)
+            return {
+              userName: c,
+              isVerified: false,
+              countryCode: user.location?.countryCode || user.country,
```
Comment (thisislawatts) [inline src/common/contributorData.ts:19]: **suggestion:** Reuse the existing [`getUserCountry` helper](https://github.com/ONEARMY/community-platform/blob/master/src/utils/getUserCountry.ts#LL3C18-L3C18)

File: src/common/contributorData.ts [hunk 5]
```diff
@@ -0,0 +1,30 @@
+import { useEffect, useState } from 'react'
```
Comment (thisislawatts) [inline src/common/contributorData.ts:1]: **question(blocking):** Should we namespace/nest these common hooks under `src/common/hooks` directory? I think it would be useful grouping mechanism. 

**issue:** The exported method is contributor**S**Data but the filename is _contributorData_. I think the filename should be _contributorsData_.

**Review by thisislawatts — CHANGES_REQUESTED** [review]

File: src/common/contributorData.ts (hunk 5 above)
Comment (AlfonsoGhislieri) [reply src/common/contributorData.ts]: Good idea, added the folder and modified the filename [870b400](https://github.com/ONEARMY/community-platform/pull/2281/commits/870b400bd8df1be34a52b5efc1fffdfb807c041b)

File: src/common/contributorData.ts (hunk 4 above)
Comment (AlfonsoGhislieri) [reply src/common/contributorData.ts]: Added in [2285d8d](https://github.com/ONEARMY/community-platform/pull/2281/commits/2285d8d08bb4a0fa64564bd25ce90cfa8409a7b7)

**Review by thisislawatts — APPROVED** [review]
