### PR TITLE
Map/cc edits

### LINKED ISSUE #698: Map - Popup opens when filtering [bug]
**Describe the bug**
Popup is visible when the map has been filtered. 

**To Reproduce**

1. Go to the map
2. Click on a marker to open the popup
3. Click somewhere else on the map to close the popup
4. Use the filters to filter markers
5. Note that the last popup you clicked on is open without a marker

**Expected behavior**
It should just filter the markers. Not open the popup you last clicked on.

**Screenshots**
Screenshot 2019-10-17 at 11 48 49

**Additional context**
I quickly tried to investigate this but no luck. Would be helpful to check through the [leaflet docs](https://leafletjs.com/reference-1.5.0.html) for methods like: `closePopup` `popupclose`

### PR DESCRIPTION
**Pull request by chrismclarke**
Few extra changes, notably:
- few small styling fixes (stop map search blocking zoom button, feedback button etc.)
- fix mock data display (description/images)
- fix popup appear on filter change (closes #698)

Todo
- test with live profile info (once working)
- remove mocks (can be done by setting `IS_MOCK` to `false` in store)
- mobile display
- logged in display (leaves gap underneath filter boxes, possibly fixed with work on new header)

### CODE REVIEW

File: src/pages/Maps/Content/Controls/index.tsx [hunk 1]
```diff
@@ -60,10 +68,12 @@ class Controls extends React.Component<IProps> {
...
     return (
       <MapFlexBar
-        px={[2, 3, 4]}
+        data-cy="map-controls"
+        ml="50px"
         py={1}
         onClick={() => {
-          // this.props.map.current.leafletElement.closePopup()
+          // close any active popup on click
+          this.injected.mapsStore.setActivePin(undefined)
```
Comment (drydenwilliams) [inline src/pages/Maps/Content/Controls/index.tsx]: 🤔 If it works 👍
