### PR TITLE
fix: replace AspectImage with Image and Boxes

### LINKED ISSUE #3407: [bug] Make how-to header image full height
**Describe the bug**
The first how-to image should be full height of the div.
This layout got broken a while ago

**See it on live **
Visit a how-to ([example](https://community.preciousplastic.com/how-to/set-up-a-machine-shop))

**Expected behaviour**
This is what it should look like
before-after

### PR DESCRIPTION
**Pull request by phlapjack**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- some images shown in the **HowTo** section were not the full height of the div, leaving a white space ('bar') at the bottom of the div
- it looks like the problem was that the `AspectImage` component auto-generates 3 divs and an img tag; one of the divs had a style of `position: relative` which was causing the image to not fill the enclosing outer div.
- the solution was to use an `Image` component instead of `AspectImage`, and to build the 3 divs manually in the code with required styling to recreate an `AspectImage` but without the trouble-causing style.

## Git Issues

Closes #3407 

## Screenshots/Videos

- image not fully filling the div
**before**
page_with_problem_before
**after**
page_with_problem_after
**image**
problem

- image that is 'very portrait'
**before**
page_with_very_portrait_before
**after**
page_with_very_portrait_after
**image**
very_portrait

- image that is 'very landscape'
**before**
page_with_very_landscape_before
**after**
page_with_very_landscape_after
**image**
very_landscape

- image that is very large
**before**
page_with_very_big_before
**after**
page_with_very_big_after
**image**
very_big

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by davehakkens** [comment]
Looks good to me 💪

File: src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx [hunk 1]
```diff
@@ -349,22 +339,45 @@ const HowtoDescription = ({ howto, loggedInUser, ...props }: IProps) => {
...
-            />
-          )}
+            ></Box>
+            <Box
+              sx={{
+                position: 'absolute',
+                top: '0',
+                bottom: '0',
+                left: '0',
+                right: '0',
```
Comment (benfurber) [inline src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx:360]: Not sure how I feel about this absolute positioning. Is there no other way?

**Review by benfurber — COMMENTED** [review]
Awesome, thanks so much for this @phlapjack. One comment, then good to go.

File: src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx (hunk 1 above)
Comment (phlapjack) [reply src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx:360]: This style was created by AspectImage previously, so I also added it to my manually-created element. It definitely affects the layout if it's not present. It might be possible to recreate this layout without using `position: absolute` but I'm hesitant to start redoing the layout...

**Comment by benfurber** [comment]
@all-contributors please add @phlapjack for code

**Comment by benfurber** [comment]
Thanks again @phlapjack, is there any other issues you can see to pick up?
